CREATE DATABASE DBELIANA USE DBELIANA CREATE TABLE CONTACTO(
    IdContacto INT IDENTITY PRIMARY KEY,
    Nombre VARCHAR(50),
    Telefono VARCHAR(50),
    Correo VARCHAR(50)
) 

--PROCEDIMIENTO ALMACENADO PARA LISTAR REGISTROS
CREATE PROCEDURE SP_LISTAR AS BEGIN
SELECT
    *
FROM
    CONTACTO
END 

--PROCEDIMIENTO ALMACENADO SELECCIONAR UN REGISTRO
CREATE PROCEDURE SP_OBTENER(@IdContacto INT) AS BEGIN
SELECT
    *
FROM
    CONTACTO
WHERE
    IdContacto = @IdContacto
END

--PROCEDIMIENTO ALMACENADO AGREGAR REGISTRO
CREATE PROCEDURE SP_GUARDAR(
    @Nombre VARCHAR(50),
    @Telefono VARCHAR(50),
    @Correo VARCHAR(50)
) AS BEGIN
INSERT INTO
    CONTACTO (Nombre, Telefono, Correo)
VALUES
    (@Nombre, @Telefono, @Correo)
END 

--PROCEDIMIENTO ALMACENADO EDITAR REGISTRO
CREATE PROCEDURE SP_ELIMINAR(
    @IdContacto INT,
    @Nombre VARCHAR(50),
    @Telefono VARCHAR(50),
    @Correo VARCHAR(50)
) AS BEGIN
UPDATE
    CONTACTO
SET
    Nombre = @Nombre,
    Telefono = @Telefono,
    Correo = @Correo
WHERE
    IdContacto = @IdContacto
END 

--PROCEDIMIENTO ALMACENADO ELIMINAR REGISTRO
CREATE PROCEDURE SP_ELIMINAR(@IdContacto INT) AS BEGIN
DELETE FROM
    CONTACTO
WHERE
    IdContacto = @IdContacto
END